DEV-432 - gbf targets field
scbd/inde.cbd.int pull request #24
Opened 2023-07-11 15:30 UTC by randyhoulahan

2023-07-11 16:22 UTC, blaisefonseca commented on app/directives/forms/edit/edit-side-event.js
> +                            $q.all([loadUser(), loadCountries(), loadOrgs(),loadConferences(),loadSubjects(),loadTargets(),loadGbfTargets(), loadLangs()]).then(function() {
loadSubjects not required

2023-07-11 16:24 UTC, blaisefonseca requested changes
please update the backend schema with the new field

2023-07-11 16:51 UTC, randyhoulahan commented on app/directives/forms/edit/edit-side-event.js
> +                            $q.all([loadUser(), loadCountries(), loadOrgs(),loadConferences(),loadSubjects(),loadTargets(),loadGbfTargets(), loadLangs()]).then(function() {
done

2023-07-12 13:07 UTC, rqk2k approved these changes

2023-07-13 13:46 UTC, merged